name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  local_auth: ^2.3.0
  camera: ^0.11.0+2
  percent_indicator: ^4.2.3
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  firebase_auth: ^5.3.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.0
  provider: ^6.1.2
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/json/blockchain/rec_market_data.json
    - assets/json/blockchain/trade_history.json
    - assets/json/blockchain/transaction_data.json
    - assets/json/research_crowdsourcing/research_projects.json
    - assets/json/research_crowdsourcing/user_health_data.json
    - assets/json/config/app_config.json
    - assets/json/localization/en.json
    - assets/json/localization/es.json

    - assets/images/serene_landscape.jpg
