name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  local_auth: ^2.3.0
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/json/blockchain/rec_market_data.json
    - assets/json/blockchain/trade_history.json
    - assets/json/blockchain/transaction_data.json
    - assets/json/research_crowdsourcing/research_projects.json
    - assets/json/research_crowdsourcing/user_health_data.json
    - assets/json/config/app_config.json
    - assets/json/localization/en.json
    - assets/json/localization/es.json

    - assets/images/serene_landscape.jpg
